### ISSUE TITLE
BLEU: ndarray reshape error 

### ISSUE THREAD

**Issue by Axe--** [obss/jury#62]
Hey, when computing BLEU score (snippet), facing reshape error in `_compute_single_pred_single_ref`.

Could you assist with the same.

```
from jury import Jury

scorer = Jury()

# [2, 5/5]
p = [
        ['dummy text', 'dummy text', 'dummy text', 'dummy text', 'dummy text'],
        ['dummy text', 'dummy text', 'dummy text', 'dummy text', 'dummy text']
    ]

# [2, 4/2]
r = [['be looking for a certain office in the building ',
      ' ask the elevator operator for directions ',
      ' be a trained detective ',
      ' be at the scene of a crime'],
     ['leave the room ',
      ' transport the notebook']]

scores = scorer(predictions=p, references=r)
```

Output:
```
Traceback (most recent call last):
  File "/home/axe/Projects/VisComSense/del.py", line 22, in <module>
    scores = scorer(predictions=p, references=r)
  File "/home/axe/VirtualEnvs/pyenv3_8/lib/python3.8/site-packages/jury/core.py", line 78, in __call__
    score = self._compute_single_score(inputs)
  File "/home/axe/VirtualEnvs/pyenv3_8/lib/python3.8/site-packages/jury/core.py", line 137, in _compute_single_score
    score = metric.compute(predictions=predictions, references=references, reduce_fn=reduce_fn)
  File "/home/axe/VirtualEnvs/pyenv3_8/lib/python3.8/site-packages/datasets/metric.py", line 404, in compute
    output = self._compute(predictions=predictions, references=references, **kwargs)
  File "/home/axe/VirtualEnvs/pyenv3_8/lib/python3.8/site-packages/jury/metrics/_core/base.py", line 325, in _compute
    result = self.evaluate(predictions=predictions, references=references, reduce_fn=reduce_fn, **eval_params)
  File "/home/axe/VirtualEnvs/pyenv3_8/lib/python3.8/site-packages/jury/metrics/bleu/bleu_for_language_generation.py", line 241, in evaluate
    return eval_fn(predictions=predictions, references=references, reduce_fn=reduce_fn, **kwargs)
  File "/home/axe/VirtualEnvs/pyenv3_8/lib/python3.8/site-packages/jury/metrics/bleu/bleu_for_language_generation.py", line 195, in _compute_multi_pred_multi_ref
    score = self._compute_single_pred_multi_ref(
  File "/home/axe/VirtualEnvs/pyenv3_8/lib/python3.8/site-packages/jury/metrics/bleu/bleu_for_language_generation.py", line 176, in _compute_single_pred_multi_ref
    return self._compute_single_pred_single_ref(
  File "/home/axe/VirtualEnvs/pyenv3_8/lib/python3.8/site-packages/jury/metrics/bleu/bleu_for_language_generation.py", line 165, in _compute_single_pred_single_ref
    predictions = predictions.reshape(
  File "/home/axe/VirtualEnvs/pyenv3_8/lib/python3.8/site-packages/jury/collator.py", line 35, in reshape
    return Collator(_seq.reshape(args).tolist(), keep=True)
ValueError: cannot reshape array of size 20 into shape (10,)

Process finished with exit code 1
```

**Comment by devrimcavusoglu** [comment]
Hey @Axe-- , thank you for bringing this out. From the snippet it seems that the trouble is for some operations with uneven size of multiple references. I will look into it ASAP!

**Comment by devrimcavusoglu** [comment]
I looked into it, and the problem is with the collator reshape. The following type of predictions list has 2 dimensions while the collator assumes it will be 1 always, like (10,) and not (10,k) (in this specific case k=2 (# of tokens))

```
p = [
        ['dummy text', 'dummy text', 'dummy text', 'dummy text', 'dummy text'],
        ['dummy text', 'dummy text', 'dummy text', 'dummy text', 'dummy text']
    ]
```

, so that's why if you add one more token in any of the examples above it will work (cuz it's making the reshaped container of dimension 1) like,

```
p_1 = [
        ['dummy text 1', 'dummy text', 'dummy text', 'dummy text', 'dummy text'],
        ['dummy text', 'dummy text', 'dummy text', 'dummy text', 'dummy text']
    ]
```
even 1 example having different number of tokens, it makes it 1 dim as the second dimension is unknown (since it differs among samples). In a simple tokenized way "dummy text" -> ["dummy", "text"] and "dummy text 1" -> ["dummy", "text", "1"]. With computing bleu score on a sufficiently large corpus, this situation is highly unlikely (all prediction tokens having the same amount), so it's an extreme case for such corpora, it's missed. Yet, I'll soon fix this, and a test case also for this. Again another wonderful catch (great edge case) :+1:  Thanks, for bringing it out :slightly_smiling_face:

**Comment by Axe--** [comment]
Interesting! The suggested trick is helpful. 
As I was adding a dummy string when model generates no text ('') esp. during initial phase of training, the issue can be mitigated.
Thanks!

**Comment by devrimcavusoglu** [comment]
@Axe-- it's currently fixed on master, I'll prep a release very soon. Thank you so much, it was a small, but a critical bug.
